USE CNFL_App;
GO

-- ==========================================================
-- 1. ELIMINAR TODOS LOS DATOS EXISTENTES
-- ==========================================================
PRINT '🗑️ Eliminando datos existentes...';
TRUNCATE TABLE ActividadesEconomicas;
GO

-- ==========================================================
-- 2. INSERTAR DATOS DE ACTIVIDADES ECONÓMICAS (SIN DUPLICADOS)
-- ==========================================================

PRINT '📌 Insertando actividades económicas...';
GO

-- Insertar solo los códigos que no existen (ahora que la tabla está vacía, todos se insertan)
INSERT INTO ActividadesEconomicas (Codigo, Nombre, Descripcion) VALUES
('1391.0', 'Fabricación de tejidos de punto y ganchillo', 'N/A'),
('1512.0', 'Fabricación de maletas, bolsos de mano y de artículos similares', 'N/A'),
('1520.0', 'Fabricación de calzado', 'N/A'),
('2393.0', 'Fabricación de otros productos de cerámica y porcelana', 'N/A'),
('2511.0', 'Fabricación de productos metálicos para uso estructural', 'N/A'),
('3100.1', 'Fabricación de muebles de madera', 'N/A'),
('3212.0', 'Fabricación de bisutería y artículos conexos', 'N/A'),
('4719.9', 'Venta al por menor en bazares y otros establecimientos no especializados n.c.p', 'N/A'),
('4742.0', 'Venta al por menor de equipo de audio y video en comercios especializados', 'N/A'),
('4764.0', 'Venta al por menor de juegos y de juguetes en almacenes especializados', 'N/A'),
('4771.2', 'Venta al por menor de zapatos en comercios especializados', 'N/A'),
('5621.0', 'Suministros de comidas por encargo', 'N/A'),
('5630.0', 'Actividades de servicio de bebidas', 'N/A'),
('9523.0', 'Reparación de calzado y artículos de cuero', 'N/A'),
('1410.9', 'Fabricación de otras prendas de vestir, excepto ropa interior y prendas de piel', 'N/A'),
('4530.0', 'Venta de partes, piezas y accesorios de vehículos automotores', 'N/A'),
('4711.2', 'Venta al por menor en minisuper, pulperias y similares', 'N/A'),
('4721.1', 'Venta al por menor de carne de bovino, porcino y sus derivados', 'N/A'),
('4721.3', 'Venta al por menor de pescados y mariscos', 'N/A'),
('4721.4', 'Venta al por menor de frutas y verduras frescas', 'N/A'),
('4721.9', 'Venta al por menor de otros alimentos', 'N/A'),
('4722.0', 'Venta al por menor de bebidas en comercios especializados', 'N/A'),
('4751.0', 'Venta al por menor de productos textiles en comercios especializados', 'N/A'),
('4752.1', 'Venta al por menor de artículos de ferretería y pinturas en comercios especializados', 'N/A'),
('4759.0', 'Venta al por menor de aparatos eléctricos de uso doméstico, muebles, equipos de iluminación y otros enseres domésticos en comercios especializados', 'N/A'),
('4761.0', 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados', 'N/A'),
('4762.0', 'Venta al por menor de grabaciones musicales y videográficas en comercios especializados', 'N/A'),
('4763.0', 'Venta al por menor de artículos de deporte en comercios especializados', 'N/A'),
('4771.1', 'Venta al por menor de prendas de vestir y artículos de cuero en almacenes especializados', 'N/A'),
('4772.0', 'Venta al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en comercios especializados', 'N/A'),
('5610.0', 'Actividades de restaurantes y de servicios móviles de comidas', 'N/A'),
('9524.0', 'Reparación de muebles y accesorios domésticos', 'N/A'),
('0130.0', 'Propagación de plantas', 'N/A'),
('0311.0', 'Pesca marítima', 'N/A'),
('1071.9', 'Elaboración de otros productos de panadería, excepto elaboración de galletas', 'N/A'),
('1811.0', 'Impresión', 'N/A'),
('3250.0', 'Fabricación de instrumentos y suministros médicos y odontológicos', 'N/A'),
('4540.0', 'Venta, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios', 'N/A'),
('4741.0', 'Venta al por menor de computadoras, equipo periféricos, programas de información y telecomunicaciones en comercios especializados', 'N/A'),
('4773.0', 'Otra venta al por menor de otros productos nuevos en comercios especializados', 'N/A'),
('4774.0', 'Venta al por menor de artículos de segunda mano', 'N/A'),
('4781.0', 'Venta al por menor en puestos de venta y mercados de: alimentos, bebidas y de productos del tabaco', 'N/A'),
('4799.0', 'Otros tipos de venta al por menor no realizada en comercios, puestos de venta o mercados', 'N/A'),
('4922.2', 'Servicios de taxi', 'N/A'),
('7420.0', 'Actividades de fotografía', 'N/A'),
('9000.0', 'Actividades creativas, artísticas y de entretenimiento', 'N/A'),
('0111.9', 'Cultivo de otros cereales, legumbres y semillas oleaginosas n.c.p', 'N/A'),
('0113.9', 'Cultivo de otras hortalizas, raíces o tubérculos n.c.p', 'N/A'),
('0114.0', 'Cultivo de caña de azúcar', 'N/A'),
('0115.0', 'Cultivo de tabaco', 'N/A'),
('0116.0', 'Cultivo de plantas de fibras', 'N/A'),
('0119.1', 'Cultivo de Flores', 'N/A'),
('0122.1', 'Cultivo de banano', 'N/A'),
('0122.3', 'Cultivo de piña', 'N/A'),
('0122.9', 'Cultivo de otras frutas tropicales y subtropicales', 'N/A'),
('0125.0', 'Cultivo de otros frutos y nueces de árboles y arbustos', 'N/A'),
('0126.1', 'Cultivo de palma africana (aceitera)', 'N/A'),
('0127.1', 'Cultivo de café', 'N/A'),
('0128.0', 'Cultivo de especies de plantas aromáticas, medicinales y farmacéuticas', 'N/A'),
('0141.1', 'Cría de ganado Bovino (vacuno) para carne', 'N/A'),
('0141.2', 'Cría de ganado Bovino (vacuno) para producción de leche cruda', 'N/A'),
('0142.0', 'Cría de caballos y otros equinos', 'N/A'),
('0144.0', 'Cría de ovejas y cabras', 'N/A'),
('0145.0', 'Cría de cerdos', 'N/A'),
('0146.2', 'Actividades de granja para la producción de huevos de gallina', 'N/A'),
('0149.0', 'Cría de otros animales', 'N/A'),
('0150.0', 'Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta)', 'N/A'),
('0162.9', 'Otras actividades de apoyo a la ganadería', 'N/A'),
('0163.1', 'Beneficio de café', 'N/A'),
('0163.9', 'Otras actividades posteriores a la cosecha', 'N/A'),
('0170.0', 'Caza ordinaria, mediante trampas y actividades de servicio conexas', 'N/A'),
('0220.0', 'Extracción de madera', 'N/A'),
('0321.0', 'Acuicultura marina', 'N/A'),
('0510.0', 'Extracción de carbón de piedra', 'N/A'),
('0620.0', 'Extracción de gas natural', 'N/A'),
('0721.0', 'Extracción de minerales metalíferos no ferrosos', 'N/A'),
('0810.0', 'Extracción de piedra, arena y arcilla', 'N/A'),
('0891.0', 'Extracción de minerales para la fabricación de abonos y productos químicos', 'N/A'),
('0893.0', 'Extracción de sal', 'N/A'),
('0899.0', 'Explotación de otras minas y canteras n.c.p', 'N/A'),
('1010.9', 'Elaboración y conservación de otro tipo de carnes n.c.p', 'N/A'),
('1020.0', 'Elaboración y conservación de pescados, crustáceos y moluscos', 'N/A'),
('1030.0', 'Elaboración y conservación de frutas, legumbres y hortalizas (vegetales)', 'N/A'),
('1040.0', 'Elaboración de aceites y grasas de origen vegetal y animal', 'N/A'),
('1050.0', 'Elaboración de productos lácteos', 'N/A'),
('1061.1', 'Beneficio de arroz', 'N/A'),
('1061.9', 'Elaboración de productos de molinería excepto arroz', 'N/A'),
('1062.0', 'Elaboración de almidones y productos derivados del almidón', 'N/A'),
('1072.0', 'Elaboración de azúcar y otros productos derivados de la caña de azúcar', 'N/A'),
('1073.0', 'Elaboración de cacao, chocolate y productos de confitería', 'N/A'),
('1074.0', 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', 'N/A'),
('1079.9', 'Elaboración de otros productos alimenticios n.c.p', 'N/A'),
('1080.0', 'Elaboración de alimentos preparados para animales', 'N/A'),
('1101.0', 'Destilación, rectificación y mezcla de bebidas alcohólicas', 'N/A'),
('1103.0', 'Elaboración de bebidas malteadas y de malta', 'N/A'),
('1104.0', 'Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas', 'N/A'),
('1200.0', 'Elaboración de productos de tabaco', 'N/A'),
('1312.0', 'Tejedura de productos textiles', 'N/A'),
('1313.0', 'Acabado de productos textiles', 'N/A'),
('1392.0', 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir', 'N/A'),
('1393.0', 'Fabricación de tapices y alfombras', 'N/A'),
('1394.0', 'Fabricación de cuerdas, cordeles, bramantes y redes', 'N/A'),
('1511.0', 'Curtido y adobo de cueros; adobo y teñido de pieles', 'N/A'),
('1610.0', 'Aserrado y acepilladura de madera', 'N/A'),
('1621.0', 'Fabricación de hojas de madera para enchapado y tableros a base de madera', 'N/A'),
('1622.0', 'Fabricación de partes y piezas de carpintería para edificios y construcciones', 'N/A'),
('1701.0', 'Fabricación de pasta de madera, papel y cartón', 'N/A'),
('1709.0', 'Fabricación de otros artículos del papel y cartón', 'N/A'),
('1820.0', 'Reproducción de grabaciones', 'N/A'),
('1920.0', 'Fabricación de los productos de la refinación del petróleo', 'N/A'),
('2011.0', 'Fabricación de sustancias químicas básicas', 'N/A'),
('2012.0', 'Fabricación de abonos y compuestos de nitrógeno', 'N/A'),
('2013.0', 'Fabricación de plásticos y de caucho sintético en formas primarias', 'N/A'),
('2021.0', 'Fabricación de plaguicidas y de otros productos químicos de uso agropecuario', 'N/A'),
('2022.0', 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas', 'N/A'),
('2023.1', 'Fabricación de jabones y detergentes, preparados para limpiar y pulir', 'N/A'),
('2023.2', 'Fabricación de perfumes y preparados de tocador', 'N/A'),
('2029.0', 'Fabricación de otros productos químicos n.c.p', 'N/A'),
('2030.0', 'Fabricación de fibras artificiales', 'N/A'),
('2100.0', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y de productos botánicos de uso farmacéutico', 'N/A'),
('2211.0', 'Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho', 'N/A'),
('2219.0', 'Fabricación de otros productos de caucho', 'N/A'),
('2220.9', 'Fabricación de otros productos de plástico', 'N/A'),
('2310.0', 'Fabricación de vidrio y de productos de vidrio', 'N/A'),
('2391.0', 'Fabricación de productos refractarios', 'N/A'),
('2392.0', 'Fabricación de material de arcilla para la construcción', 'N/A'),
('2394.0', 'Fabricación de cemento, de la cal y del yeso', 'N/A'),
('2395.0', 'Fabricación de artículos de hormigón, de cemento y de yeso', 'N/A'),
('2396.0', 'Corte, tallado y acabado de la piedra', 'N/A'),
('2399.0', 'Fabricación de otros productos minerales no metálicos n.c.p', 'N/A'),
('2410.0', 'Industrias básicas de hierro y acero', 'N/A'),
('2420.0', 'Fabricación de productos primarios de metales preciosos y metales no ferrosos', 'N/A'),
('2431.0', 'Fundición de hierro y acero', 'N/A'),
('2432.0', 'Fundición de metales no ferrosos', 'N/A'),
('2512.0', 'Fabricación de tanques, depósitos y recipientes de metal', 'N/A'),
('2513.0', 'Fabricación de los generadores del vapor, excepto calderas de agua caliente para calefacción central', 'N/A'),
('2520.0', 'Fabricación de armas y municiones', 'N/A'),
('2592.0', 'Tratamiento y revestimiento de metales', 'N/A'),
('2599.0', 'Fabricación de otros productos de metal n.c.p', 'N/A'),
('2610.0', 'Fabricación de componentes y tableros electrónicos', 'N/A'),
('2630.0', 'Fabricación de equipos de comunicaciones', 'N/A'),
('2651.0', 'Fabricación de equipos de medición, prueba, verificación, navegación y de equipo de control', 'N/A'),
('2652.0', 'Fabricación de relojes', 'N/A'),
('2670.0', 'Fabricación de instrumentos ópticos de equipo fotográfico', 'N/A'),
('2710.0', 'Fabricación de motores eléctricos, generadores, transformadores eléctricos y aparatos de distribución y control de la energía eléctrica', 'N/A'),
('2720.0', 'Fabricación de baterías y acumuladores', 'N/A'),
('2732.0', 'Fabricación de otros hilos y cables eléctricos', 'N/A'),
('2740.0', 'Fabricación de equipos de iluminación eléctricos', 'N/A'),
('2750.0', 'Fabricación de aparatos de uso doméstico', 'N/A'),
('2790.0', 'Fabricación de otro equipo eléctrico', 'N/A'),
('2811.0', 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', 'N/A'),
('2813.0', 'Fabricación de otras bombas, compresores, grifos y válvulas', 'N/A'),
('2815.0', 'Fabricación de hornos, hogueras y quemadores', 'N/A'),
('2817.0', 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipos periféricos)', 'N/A'),
('2821.0', 'Fabricación de maquinaria agropecuaria y forestal', 'N/A'),
('2822.0', 'Fabricación de maquinarias para la conformación de metales y de máquinas herramientas', 'N/A'),
('2823.0', 'Fabricación de maquinaria para metalúrgica', 'N/A'),
('2824.0', 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', 'N/A'),
('2825.0', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'N/A'),
('2826.0', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'N/A'),
('2829.0', 'Fabricación de otros tipos de maquinaria de uso especial', 'N/A'),
('2910.0', 'Fabricación de vehículos automotores', 'N/A'),
('2920.0', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques', 'N/A'),
('2930.0', 'Fabricación de partes y accesorios para motores de vehículos', 'N/A'),
('3012.0', 'Construcción de embarcaciones de recreo y deporte', 'N/A'),
('3020.0', 'Fabricación de locomotoras y de material rodante', 'N/A'),
('3030.0', 'Fabricación de aeronaves y naves espaciales y de maquinaria conexa', 'N/A'),
('3091.0', 'Fabricación de motocicletas', 'N/A'),
('3092.0', 'Fabricación de bicicletas y sillas de ruedas para personas con discapacidad', 'N/A'),
('3099.0', 'Fabricación de otros tipos de equipo de transporte n.c.p', 'N/A'),
('3100.9', 'Fabricación de muebles de otro tipo de material (excepto de madera, piedra, cemento o cerámica)', 'N/A'),
('3211.0', 'Fabricación de joyas y artículos conexos', 'N/A'),
('3220.0', 'Fabricación de instrumentos musicales', 'N/A'),
('3230.0', 'Fabricación de artículos de deporte', 'N/A'),
('3240.0', 'Fabricación de juegos y juguetes', 'N/A'),
('3290.0', 'Otras industrias manufactureras n.c.p', 'N/A'),
('3311.0', 'Reparación de productos elaborados de metal', 'N/A'),
('3312.0', 'Reparación de maquinaria', 'N/A'),
('3314.0', 'Reparación de equipo eléctrico', 'N/A'),
('3315.0', 'Reparación de equipo de transporte, excepto los vehículos automotores', 'N/A'),
('3510.0', 'Generación, transmisión y distribución de energía eléctrica', 'N/A'),
('3520.0', 'Fabricación de gas; distribución de combustibles gaseosos por tuberías', 'N/A'),
('3530.0', 'Suministro de vapor y aire acondicionado', 'N/A'),
('3700.0', 'Evacuación de aguas residuales', 'N/A'),
('3811.0', 'Recolección de desechos no peligrosos', 'N/A'),
('4100.0', 'Construcción de edificios', 'N/A'),
('4210.0', 'Construcción de carreteras y vías férreas', 'N/A'),
('4311.0', 'Demolición', 'N/A'),
('4312.0', 'Preparación del terreno', 'N/A'),
('4390.0', 'Otras actividades especializadas de la construcción', 'N/A'),
('4610.0', 'Venta al por mayor a cambio de una retribución o por contrato', 'N/A'),
('4641.1', 'Venta al por mayor de productos textiles y prendas de vestir', 'N/A'),
('4649.1', 'Venta al por mayor de aparatos, artículos y equipo de uso doméstico', 'N/A'),
('4651.0', 'Venta al por mayor de computadoras, equipo informático periférico y programas informáticos', 'N/A'),
('4652.0', 'Venta al por mayor de equipo, partes y piezas electrónicas y de telecomunicaciones', 'N/A'),
('4662.0', 'Venta al por mayor de metales y de minerales metalíferos', 'N/A'),
('4663.0', 'Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción', 'N/A'),
('4669.1', 'Venta al por mayor de fertilizantes y productos agroquímicos', 'N/A'),
('4669.9', 'Venta al por mayor de basura, desechos y otros productos n.c.p', 'N/A'),
('4690.0', 'Venta al por mayor de otros productos no especializada', 'N/A'),
('4711.1', 'Venta al por menor en supermercados, almacenes y similares', 'N/A'),
('4719.1', 'Venta al por menor en tiendas por departamentos', 'N/A'),
('4723.0', 'Venta al por menor de tabaco en comercios especializados', 'N/A'),
('4730.0', 'Venta al por menor de combustibles para vehículos automotores en comercios especializados', 'N/A'),
('4752.2', 'Venta al por menor de productos de vidrio en comercios especializados', 'N/A'),
('4753.0', 'Venta al por menor de tapices, alfombras, cubrimientos para paredes y pisos en comercios especializados', 'N/A'),
('4911.0', 'Transporte de pasajeros por ferrocarril', 'N/A'),
('4921.0', 'Transporte terrestre de pasajeros del área urbana, suburbana por vía terrestre', 'N/A'),
('4922.1', 'Transporte terrestre de estudiantes y de empleados', 'N/A'),
('4922.3', 'Transporte terrestre no regular de pasajeros, en buses', 'N/A'),
('4923.1', 'Transporte terrestre local e internacional de contenedores', 'N/A'),
('4923.9', 'Otro transporte de carga n.c.p', 'N/A'),
('4930.0', 'Transporte por tuberías', 'N/A'),
('5012.0', 'Transporte marítimo y de cabotaje de carga', 'N/A'),
('5110.0', 'Transporte de pasajeros por vía aérea', 'N/A'),
('5120.0', 'Transporte de carga por vía aérea', 'N/A'),
('5210.0', 'Almacenamiento y depósito', 'N/A'),
('5221.1', 'Remolque y asistencia para vehículo destinado al transporte terrestre', 'N/A'),
('5221.2', 'Servicios de estacionamientos y garajes', 'N/A'),
('5221.9', 'Servicios de administración de carreteras, puentes y otros servicios auxiliares', 'N/A'),
('5223.0', 'Actividades de servicio secundario de transporte por vía aérea', 'N/A'),
('5224.0', 'Manipulación de carga', 'N/A'),
('5229.0', 'Otras actividades de apoyo al transporte', 'N/A'),
('5310.0', 'Servicios postales (Correo)', 'N/A'),
('5510.1', 'Actividades de alojamiento para estancias cortas en hoteles y moteles', 'N/A'),
('5510.9', 'Otras actividades de alojamiento para estancias cortas n.c.p', 'N/A'),
('5590.0', 'Otras actividades de alojamientos', 'N/A'),
('5811.0', 'Edición de libros', 'N/A'),
('5813.0', 'Edición de periódicos, diarios y revistas', 'N/A'),
('5911.0', 'Actividades de producción de películas cinematográficas, videos y programas de televisión', 'N/A'),
('5914.0', 'Actividades de proyección de películas', 'N/A'),
('5920.0', 'Actividades de grabación y publicación de grabaciones sonoras', 'N/A'),
('6010.0', 'Transmisiones de radio', 'N/A'),
('6020.0', 'Programación y transmisión de televisión', 'N/A'),
('6110.0', 'Actividades de telecomunicaciones alámbricas', 'N/A'),
('6120.0', 'Actividades de telecomunicaciones inalámbricas', 'N/A'),
('6190.1', 'Servicios de café internet', 'N/A'),
('6190.9', 'Otras actividades de telecomunicación', 'N/A'),
('6201.0', 'Actividades de programación informática', 'N/A'),
('6202.0', 'Actividades de consultoría informática y gestión de instalaciones informáticas', 'N/A'),
('6209.0', 'Otras actividades de la tecnología de información y servicio informáticos', 'N/A'),
('6311.0', 'Procesamiento de datos, hospedaje y actividades conexas', 'N/A'),
('6391.0', 'Actividades de agencias de noticias', 'N/A'),
('6411.0', 'Banca Central', 'N/A'),
('6419.0', 'Otros tipos de intermediación monetaria', 'N/A'),
('6420.0', 'Actividades de sociedades de cartera', 'N/A'),
('6430.0', 'Fondo y sociedades de inversión y entidades financieras similares', 'N/A'),
('6491.0', 'Arrendamiento financiero', 'N/A'),
('6492.0', 'Otros tipos de crédito', 'N/A'),
('6499.0', 'Otros tipos de crédito', 'N/A'),
('6511.0', 'Seguros de vida', 'N/A'),
('6512.0', 'Seguros generales', 'N/A'),
('6530.0', 'Fondos de pensión', 'N/A'),
('6611.0', 'Administración de mercados financieros', 'N/A'),
('6612.0', 'Corretaje de valores y de contratos de productos básicos', 'N/A'),
('6619.0', 'Otras actividades auxiliares a las actividades de servicios financieros', 'N/A'),
('6622.0', 'Actividades de agentes y corredores de seguro', 'N/A'),
('6629.0', 'Otras actividades auxiliares de seguros y fondos de pensiones', 'N/A'),
('6810.0', 'Actividades inmobiliarias con bienes propios o arrendados', 'N/A'),
('6820.0', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', 'N/A'),
('6920.0', 'Actividades de contabilidad, tenencia de libros y auditorías; consultoría fiscal', 'N/A'),
('7010.0', 'Actividades de oficinas principales', 'N/A'),
('7020.0', 'Actividades de consultoría en gestión', 'N/A'),
('7110.0', 'Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica', 'N/A'),
('7120.0', 'Ensayos y análisis técnicos', 'N/A'),
('7210.0', 'Investigación y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', 'N/A'),
('7220.0', 'Investigación y desarrollo experimental en el campo de las ciencias sociales y las humanidades', 'N/A'),
('7310.0', 'Publicidad', 'N/A'),
('7320.0', 'Estudios de mercados y encuestas de opinión pública', 'N/A'),
('7410.0', 'Actividades especializadas de diseño', 'N/A'),
('7490.0', 'Otras actividades profesionales, científicas y técnicas n.c.p.', 'N/A'),
('7500.0', 'Actividades veterinarias', 'N/A'),
('7710.1', 'Alquiler de automóviles sin conductor', 'N/A'),
('7721.0', 'Alquiler y arrendamiento de equipo recreativo y deportivo', 'N/A'),
('7722.0', 'Alquiler de cintas de vídeo y discos', 'N/A'),
('7729.0', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos', 'N/A'),
('7730.0', 'Alquiler y arrendamiento de otros tipo de maquinaria, equipo y bienes tangibles', 'N/A'),
('7740.0', 'Arrendamiento de propiedad intelectual y productos similares excepto obras protegidas por derechos de autor', 'N/A'),
('7830.0', 'Otras actividades de dotación de recursos humanos', 'N/A'),
('7911.0', 'Actividades de agencias de viajes', 'N/A'),
('7912.0', 'Actividades de operadores turísticos', 'N/A'),
('8010.0', 'Actividades de seguridad privada', 'N/A'),
('8110.0', 'Actividades combinadas de apoyo a instalaciones', 'N/A'),
('8121.0', 'Limpieza general de edificios', 'N/A'),
('8129.0', 'Otras actividades de limpieza de edificios e instalaciones industriales', 'N/A'),
('8130.0', 'Actividades de paisajismo y servicios de mantenimiento conexos', 'N/A'),
('8219.0', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina', 'N/A'),
('8220.0', 'Actividades de centros de llamadas', 'N/A'),
('8291.0', 'Actividades de agencias de cobro y agencias de calificación crediticia', 'N/A'),
('8292.0', 'Actividades de envasado y empacado', 'N/A'),
('8299.0', 'Otras actividades de servicios de apoyo a las empresas n.c.p', 'N/A'),
('8411.0', 'Actividades de la administración pública en general', 'N/A'),
('8413.0', 'Regulación y facilitación de la actividad económica', 'N/A'),
('8421.0', 'Relaciones exteriores', 'N/A'),
('8423.0', 'Actividades de mantenimiento del orden público y de seguridad', 'N/A'),
('8430.0', 'Actividades de planes de seguridad social de afiliación obligatoria', 'N/A'),
('8510.0', 'Enseñanza preescolar y primaria', 'N/A'),
('8521.0', 'Enseñanza secundaria de formación general', 'N/A'),
('8522.0', 'Enseñanza de formación técnica y profesional', 'N/A'),
('8530.1', 'Enseñanza universitaria', 'N/A'),
('8530.2', 'Enseñanza parauniversitaria', 'N/A'),
('8541.0', 'Educación deportiva y recreativa', 'N/A'),
('8542.0', 'Educación cultural', 'N/A'),
('8549.0', 'Otros tipos de enseñanza n.c.p', 'N/A'),
('8550.0', 'Actividades de apoyo a la enseñanza', 'N/A'),
('8610.0', 'Actividades de hospitales', 'N/A'),
('8620.1', 'Actividades de médicos', 'N/A'),
('8620.2', 'Actividades de odontólogos', 'N/A'),
('8690.1', 'Laboratorios médicos y de diagnóstico', 'N/A'),
('8690.9', 'Otras actividades relacionadas con la salud humana', 'N/A'),
('8720.0', 'Actividades de atención en instituciones para personas con retraso mental, enfermos mentales y toxicómanos', 'N/A'),
('8790.0', 'Otras actividades de atención en instituciones n.c.p', 'N/A'),
('8810.0', 'Asistencia social sin alojamiento para el adulto mayor y personas con discapacidad', 'N/A'),
('8890.0', 'Otras actividades de asistencia social sin alojamiento n.c.p', 'N/A'),
('9101.0', 'Actividades de Bibliotecas y archivos', 'N/A'),
('9102.0', 'Actividades de museos y preservación de lugares históricos', 'N/A'),
('9103.0', 'Actividades de jardines botánicos, zoológicos y parques naturales', 'N/A'),
('9200.0', 'Actividades de juego de azar y apuestas', 'N/A'),
('9311.0', 'Gestión de instalaciones deportivas', 'N/A'),
('9319.0', 'Otras actividades deportivas', 'N/A'),
('9329.0', 'Otras actividades de esparcimiento y recreativas n.c.p', 'N/A'),
('9411.0', 'Actividades de Asociaciones empresariales y de empleadores', 'N/A'),
('9412.0', 'Actividades de asociaciones profesionales', 'N/A'),
('9420.0', 'Actividades de sindicatos', 'N/A'),
('9491.0', 'Actividades de organizaciones religiosas', 'N/A'),
('9492.0', 'Actividades de organizaciones políticas', 'N/A'),
('9499.0', 'Actividades de otras asociaciones n.c.p', 'N/A'),
('9511.0', 'Reparación de computadoras y equipo periférico', 'N/A'),
('9512.0', 'Reparación de equipos de comunicaciones', 'N/A'),
('9521.0', 'Reparación de aparatos electrónicos de consumo eléctrico', 'N/A'),
('9522.0', 'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería', 'N/A'),
('9529.0', 'Reparación de otros bienes personales y enseres domésticos n.c.p', 'N/A'),
('9601.0', 'Lavado y limpieza, incluida la limpieza en seco, de productos textiles y piel', 'N/A'),
('9602.0', 'Actividades de peluquería y otros tratamientos de belleza', 'N/A'),
('9603.0', 'Funerales y actividades conexas', 'N/A'),
('9609.0', 'Otras actividades de servicios personales n.c.p', 'N/A'),
('9700.0', 'Actividades de los hogares como empleadores de personal doméstico', 'N/A'),
('9900.0', 'Actividades de organizaciones y órganos extraterritoriales', 'N/A'),
('0000.1', 'Actividades preoperativas o de organización', 'N/A'),
('0000.2', 'Servicios digitales o de telecomunicaciones e intangibles prestados desde el exterior por proveedores', 'N/A'),
('0000.3', 'Servicios digitales o de telecomunicaciones e intangibles prestados desde el exterior por intermediarios', 'N/A');

PRINT '✅ Todas las actividades económicas insertadas correctamente.';
GO

-- ==========================================================
-- 3. VERIFICAR
-- ==========================================================
PRINT '📊 Total de actividades insertadas:';
SELECT COUNT(*) AS TotalActividades FROM ActividadesEconomicas;
GO

-- Mostrar las primeras 10 actividades
PRINT '📊 Primeras 10 actividades:';
SELECT TOP 10 Codigo, Nombre FROM ActividadesEconomicas ORDER BY Codigo;
GO