// ==========================================
// IDIOMAS - TRADUCCIONES DE TODA LA APP
// ==========================================

var idiomas = {
    es: {
        // ===== MENÚ =====
        'menu_inicio': 'Inicio',
        'menu_tramites': 'Trámites',
        'menu_pagos': 'Pagos',
        'menu_tienda': 'Tienda',
        'menu_reportes': 'Reportes',
        'menu_cuenta': 'Cuenta',

        // ===== GENERALES =====
        'volver': 'Volver',
        'guardar': 'Guardar Cambios',
        'cancelar': 'Cancelar',
        'enviar': 'Enviar',
        'cargando': 'Cargando...',
        'cerrar': 'Cerrar',
        'confirmar': 'Confirmar',

        // ===== INICIO =====
        'inicio_saludo': 'Hola,',
        'factura_pendiente': 'FACTURA PENDIENTE',
        'vence_el': 'Vence el',
        'ver_detalle': 'Ver detalle',
        'pagar_ahora': 'Pagar ahora',
        'mis_servicios': 'Mis servicios asociados',
        'normal': 'Normal',
        'prevencion': 'Prevención',
        'incidente': 'Incidente',
        'consumo_kwh': 'Consumo kWh',
        'ultimos_6_meses': 'Últimos 6 meses',
        '31_dias': '31 días',
        'lecturas': 'Lecturas',
        'consulta_medidor': 'Consulta al medidor',
        'ultima_lectura': 'Última lectura',
        'acumulado_mes': 'Acumulado del mes',
        'costo_estimado': 'Costo estimado',
        'promedio_mensual': 'Promedio mensual',
        'ahorro': '12% menos que el mes anterior · ¡buen ahorro!',

        // ===== TRÁMITES =====
        'tramites_titulo': 'Trámites',
        'tramites_subtitulo': '16 solicitudes en línea, sin filas.',
        'mis_tramites_activos': 'Mis trámites activos',
        'solicitud_servicio': 'Solicitud servicio nuevo monofásico',
        'estado': 'Estado',
        'en_proceso': 'En proceso',
        'catalogo_tramites': 'Catálogo de trámites',
        'cambio_nombre': 'Cambio de nombre de abonado',
        'desconexion_reconexion': 'Desconexión y reconexión',
        'solicitud_servicio_nuevo': 'Solicitud de servicio nuevo',
        'traslado_medidor': 'Traslado de medidor',
        'traspaso_servicio': 'Traspaso de servicio eléctrico',
        'reclamo_danos': 'Reclamo por daños',

        // ===== PAGOS =====
        'pagos_titulo': 'Mis Pagos',
        'historial_pagos': 'Historial de Pagos',
        'consulta_paga': 'Consulta y paga tus facturas en segundos.',
        'pendiente': 'PENDIENTE',
        'pagada': 'PAGADA',
        'pago_exitoso': '✓ Pago realizado con éxito',
        'sinpe_movil': 'SINPE Móvil',
        'iban': 'IBAN',
        'tarjeta': 'Tarjeta',
        'pago_sinpe': 'Pago con SINPE Móvil',
        'pago_iban': 'Pago por Transferencia IBAN',
        'pago_tarjeta': 'Pago con Tarjeta',
        'producto_factura': 'Producto/Factura',
        'monto_pagar': 'Monto a pagar',
        'confirmar_pago': 'Confirmar pago',
        'confirmar_transferencia': 'Confirmar transferencia',
        'nombre_titular': 'Nombre del titular',
        'cuenta_destino': 'Cuenta destino',
        'monto_transferir': 'Monto a transferir',
        'numero_tarjeta': 'Número de tarjeta',
        'fecha_expiracion': 'Fecha expiración',
        'cw': 'CVV',
        'pagar': 'Pagar',

        // ===== TIENDA =====
        'tienda_titulo': 'Productos y servicios',
        'compra_facil': 'Compra fácil, paga con tu factura.',
        'hogar_360': 'HOGAR 360°',
        'cargador_auto': 'Cargador para tu auto eléctrico',
        'instalacion_certificada': 'Instalación certificada.',
        'solicitar_cotizacion': 'Solicitar cotización →',
        'cnfl_te_asiste': 'CNFL TE ASISTE',
        'seguros': 'Seguros',
        '5g': '5G',
        'vigilancia': 'Vigilancia',
        'consumo_verde': 'Consumo Verde',
        'marketplace': 'Marketplace',
        'cargar_factura': 'Cargar a factura',
        'aire_acondicionado': 'Aire acondicionado Inverter',
        'kit_iluminacion': 'Kit iluminación LED',
        'cargador_ev': 'Cargador EV residencial',
        'supresor_picos': 'Supresor de picos',
        'panel_solar': 'Panel Solar',
        'termostato_smart': 'Termostato Smart',

        // ===== REPORTES =====
        'reportes_titulo': 'Reportes y mapa',
        'reportes_subtitulo': 'Reporta una avería con foto y ubicación GPS.',
        'averias': 'Averías',
        'recarga_electrica': 'Recarga eléctrica',
        'puntos_verdes': 'Puntos verdes',
        'estado_mis_averias': 'ESTADO DE MIS AVERÍAS',
        'nuevo_reporte': 'NUEVO REPORTE',
        'averia_alumbrado': 'Avería en alumbrado público',
        'averia_propia': 'Avería eléctrica propia',
        'averia_ajena': 'Avería eléctrica ajena',
        'foto_poste': 'Foto + número de poste',
        'tu_nise': 'En tu NISE registrado',
        'sube_fotos': 'Sube fotos y ubicación GPS',
        'titulo_averia': 'Título de la avería',
        'direccion': 'Dirección',
        'tipo_problema': 'Tipo de problema',
        'descripcion_problema': 'Descripción del problema',
        'adjuntar_foto': 'Adjuntar foto / video',
        'seleccionar_archivo': 'Seleccionar archivo',
        'enviar_reporte': 'Enviar Reporte',
        'obtener_ubicacion': 'Obtener mi ubicación en tiempo real',

        // ===== PERFIL / CUENTA =====
        'perfil_titulo': 'Mi Cuenta',
        'datos_protegidos': 'Datos protegidos',
        'cifrado_biometria': 'Cifrado extremo a extremo · biometría',
        'mi_actividad': 'Mi actividad',
        'historial_compras': 'Historial de compras',
        'suscripciones': 'Suscripciones',
        'activas_inactivas': '2 activas · 1 inactiva',
        'editar_datos': 'Editar Mis Datos',
        'nombre': 'Nombre',
        'apellidos': 'Apellidos',
        'telefono': 'Teléfono',
        'correo': 'Correo',
        'guardar_cambios': 'Guardar Cambios',
        'cerrar_sesion': 'Cerrar Sesión',

        // ===== FACTURAS =====
        'detalle_factura': 'Detalle de Factura',
        'revisa_info': 'Revisa la información completa de tu factura.',
        'tarifa': 'Tarifa',
        'consumo': 'Consumo',
        'vencimiento': 'Vencimiento',
        'deseas_pagar': '¿Deseas pagar esta factura ahora?',
        'residencial': 'Residencial',

        // ===== SUSCRIPCIONES =====
        'suscripciones_titulo': 'Suscripciones',
        'suscripciones_subtitulo': 'Administra tus servicios contratados.',
        'mis_suscripciones': 'MIS SUSCRIPCIONES',
        'internet_5g': 'Internet 5G',
        'plan_hogar': 'Plan Hogar 300MB',
        'videovigilancia': 'Videovigilancia',
        'plan_hogar_pro': 'Plan Hogar Pro',
        'seguro_hogar': 'Seguro Hogar',
        'gestionar': 'Gestionar',
        'servicios_contratados': 'Servicios contratados',
        'servicios_activos': 'SERVICIOS ACTIVOS',
        'servicio_electrico': 'Servicio Eléctrico',
        'activo': 'Activo',

        // ===== CHAT / ASISTENTE =====
        'asistente_titulo': 'Asistente Virtual',
        'asistente_subtitulo': '800 ENERGÍA · 1026',
        'asistente_saludo': '¡Hola! Soy tu asistente virtual CNFL.',
        'escribe_consulta': 'Escribe tu consulta...',
        'enviar_mensaje': 'Enviar',
        'pregunta_factura': '¿Cómo puedo pagar mi factura?',
        'pregunta_averia': '¿Cómo reporto una avería?',
        'pregunta_consumo': '¿Cómo veo mi consumo?',
        'pregunta_suspension': '¿Cuándo hay suspensiones?',

        // ===== CALCULADORA =====
        'calculadora_titulo': 'Calculadora energética',
        'calculadora_subtitulo': 'Estima el costo de tus equipos.',
        'cuantos_kwh': '¿Cuántos kWh consumiste?',
        'calcular_costo': 'Calcular costo estimado',
        'costo_aproximado': 'El costo aproximado es:',

        // ===== NOTIFICACIONES =====
        'notificaciones_titulo': 'Notificaciones',
        'notificaciones_subtitulo': 'Tus alertas y notificaciones del sistema'
    },

    en: {
        // ===== MENÚ =====
        'menu_inicio': 'Home',
        'menu_tramites': 'Requests',
        'menu_pagos': 'Payments',
        'menu_tienda': 'Store',
        'menu_reportes': 'Reports',
        'menu_cuenta': 'Account',

        // ===== GENERALES =====
        'volver': 'Back',
        'guardar': 'Save Changes',
        'cancelar': 'Cancel',
        'enviar': 'Send',
        'cargando': 'Loading...',
        'cerrar': 'Close',
        'confirmar': 'Confirm',

        // ===== INICIO =====
        'inicio_saludo': 'Hello,',
        'factura_pendiente': 'PENDING BILL',
        'vence_el': 'Due on',
        'ver_detalle': 'View details',
        'pagar_ahora': 'Pay now',
        'mis_servicios': 'My associated services',
        'normal': 'Normal',
        'prevencion': 'Prevention',
        'incidente': 'Incident',
        'consumo_kwh': 'Consumption kWh',
        'ultimos_6_meses': 'Last 6 months',
        '31_dias': '31 days',
        'lecturas': 'Readings',
        'consulta_medidor': 'Meter consultation',
        'ultima_lectura': 'Last reading',
        'acumulado_mes': 'Month accumulated',
        'costo_estimado': 'Estimated cost',
        'promedio_mensual': 'Monthly average',
        'ahorro': '12% less than previous month · good savings!',

        // ===== TRÁMITES =====
        'tramites_titulo': 'Requests',
        'tramites_subtitulo': '16 online requests, no lines.',
        'mis_tramites_activos': 'My active requests',
        'solicitud_servicio': 'New single-phase service request',
        'estado': 'Status',
        'en_proceso': 'In process',
        'catalogo_tramites': 'Service catalog',
        'cambio_nombre': 'Subscriber name change',
        'desconexion_reconexion': 'Disconnection and reconnection',
        'solicitud_servicio_nuevo': 'New service request',
        'traslado_medidor': 'Meter transfer',
        'traspaso_servicio': 'Electric service transfer',
        'reclamo_danos': 'Damage claim',

        // ===== PAGOS =====
        'pagos_titulo': 'My Payments',
        'historial_pagos': 'Payment History',
        'consulta_paga': 'Check and pay your bills in seconds.',
        'pendiente': 'PENDING',
        'pagada': 'PAID',
        'pago_exitoso': '✓ Payment successful',
        'sinpe_movil': 'SINPE Mobile',
        'iban': 'IBAN',
        'tarjeta': 'Card',
        'pago_sinpe': 'SINPE Mobile Payment',
        'pago_iban': 'IBAN Transfer Payment',
        'pago_tarjeta': 'Card Payment',
        'producto_factura': 'Product/Bill',
        'monto_pagar': 'Amount to pay',
        'confirmar_pago': 'Confirm payment',
        'confirmar_transferencia': 'Confirm transfer',
        'nombre_titular': 'Account holder name',
        'cuenta_destino': 'Destination account',
        'monto_transferir': 'Amount to transfer',
        'numero_tarjeta': 'Card number',
        'fecha_expiracion': 'Expiration date',
        'cw': 'CVV',
        'pagar': 'Pay',

        // ===== TIENDA =====
        'tienda_titulo': 'Products and services',
        'compra_facil': 'Easy purchase, pay with your bill.',
        'hogar_360': 'HOME 360°',
        'cargador_auto': 'Charger for your electric car',
        'instalacion_certificada': 'Certified installation.',
        'solicitar_cotizacion': 'Request quote →',
        'cnfl_te_asiste': 'CNFL ASSISTS YOU',
        'seguros': 'Insurance',
        '5g': '5G',
        'vigilancia': 'Surveillance',
        'consumo_verde': 'Green Consumption',
        'marketplace': 'Marketplace',
        'cargar_factura': 'Charge to bill',
        'aire_acondicionado': 'Inverter Air Conditioner',
        'kit_iluminacion': 'LED Lighting Kit',
        'cargador_ev': 'Residential EV Charger',
        'supresor_picos': 'Surge protector',
        'panel_solar': 'Solar Panel',
        'termostato_smart': 'Smart Thermostat',

        // ===== REPORTES =====
        'reportes_titulo': 'Reports and map',
        'reportes_subtitulo': 'Report a fault with photo and GPS location.',
        'averias': 'Faults',
        'recarga_electrica': 'Electric recharge',
        'puntos_verdes': 'Green points',
        'estado_mis_averias': 'MY FAULTS STATUS',
        'nuevo_reporte': 'NEW REPORT',
        'averia_alumbrado': 'Street lighting fault',
        'averia_propia': 'Own electrical fault',
        'averia_ajena': 'Third-party electrical fault',
        'foto_poste': 'Photo + pole number',
        'tu_nise': 'In your registered NISE',
        'sube_fotos': 'Upload photos and GPS location',
        'titulo_averia': 'Fault title',
        'direccion': 'Address',
        'tipo_problema': 'Problem type',
        'descripcion_problema': 'Problem description',
        'adjuntar_foto': 'Attach photo / video',
        'seleccionar_archivo': 'Select file',
        'enviar_reporte': 'Send Report',
        'obtener_ubicacion': 'Get my real-time location',

        // ===== PERFIL / CUENTA =====
        'perfil_titulo': 'My Account',
        'datos_protegidos': 'Protected data',
        'cifrado_biometria': 'End-to-end encryption · biometrics',
        'mi_actividad': 'My activity',
        'historial_compras': 'Purchase history',
        'suscripciones': 'Subscriptions',
        'activas_inactivas': '2 active · 1 inactive',
        'editar_datos': 'Edit My Data',
        'nombre': 'Name',
        'apellidos': 'Last name',
        'telefono': 'Phone',
        'correo': 'Email',
        'guardar_cambios': 'Save Changes',
        'cerrar_sesion': 'Logout',

        // ===== FACTURAS =====
        'detalle_factura': 'Bill Details',
        'revisa_info': 'Check the complete information of your bill.',
        'tarifa': 'Rate',
        'consumo': 'Consumption',
        'vencimiento': 'Due date',
        'deseas_pagar': 'Do you want to pay this bill now?',
        'residencial': 'Residential',

        // ===== SUSCRIPCIONES =====
        'suscripciones_titulo': 'Subscriptions',
        'suscripciones_subtitulo': 'Manage your contracted services.',
        'mis_suscripciones': 'MY SUBSCRIPTIONS',
        'internet_5g': '5G Internet',
        'plan_hogar': 'Home Plan 300MB',
        'videovigilancia': 'Video surveillance',
        'plan_hogar_pro': 'Home Pro Plan',
        'seguro_hogar': 'Home Insurance',
        'gestionar': 'Manage',
        'servicios_contratados': 'Contracted services',
        'servicios_activos': 'ACTIVE SERVICES',
        'servicio_electrico': 'Electrical Service',
        'activo': 'Active',

        // ===== CHAT / ASISTENTE =====
        'asistente_titulo': 'Virtual Assistant',
        'asistente_subtitulo': '800 ENERGÍA · 1026',
        'asistente_saludo': 'Hello! I\'m your CNFL virtual assistant.',
        'escribe_consulta': 'Write your question...',
        'enviar_mensaje': 'Send',
        'pregunta_factura': 'How can I pay my bill?',
        'pregunta_averia': 'How do I report a fault?',
        'pregunta_consumo': 'How do I see my consumption?',
        'pregunta_suspension': 'When are there suspensions?',

        // ===== CALCULADORA =====
        'calculadora_titulo': 'Energy Calculator',
        'calculadora_subtitulo': 'Estimate the cost of your equipment.',
        'cuantos_kwh': 'How many kWh did you consume?',
        'calcular_costo': 'Calculate estimated cost',
        'costo_aproximado': 'The approximate cost is:',

        // ===== NOTIFICACIONES =====
        'notificaciones_titulo': 'Notifications',
        'notificaciones_subtitulo': 'Your alerts and system notifications'
    }
};